### ISSUE TITLE
Tables from Spatialite don't show up

### ISSUE THREAD

**Issue by geraldo** [spaciandd/franchise#2]
Tables from Spatialite files should be listed the same way as SQLite tables do. Check out the standard behaviour from https://franchise.cloud/app/:

![franchise_spatialite](https://user-images.githubusercontent.com/336371/157841081-22d04095-cc28-45e4-94d6-1889a2bbaa82.png)

Related to this I would like to know which file loader now is used in case you load a SQLite file. As it seems to me in any now it does use Spatialite engine, as the table selector dropdown now also disappeared from when loading SQLite files.

**Comment by spaciandd** [comment]
This is also working now as expected
