### ISSUE TITLE
Error when using function ST_TRANSFORM

### ISSUE THREAD

**Issue by geraldo** [spaciandd/franchise#5]
When trying to reprojecting coordinates into difference projection using ST_TRANSFORM like that:

`SELECT name, X(transform(geometry,4326)) AS long, Y(transform(geometry,4326)) AS lat FROM table` 

I get the following error in Javscript console:

> Error: ST_Transform exception - PROJ reports "proj_create: no database context specified".

**Comment by geraldo** [comment]
Maybe proj dependency is missing? At least spatialite documenation does mention it at `ST_Transform` function: http://www.gaia-gis.it/gaia-sins/spatialite-sql-5.0.1.html

**Comment by spaciandd** [comment]
@geraldo you can pull latest code it is fixed now

**Comment by geraldo** [comment]
Great, this does work now! Here a [small test database](https://cloud.servus.at/s/F5o2MjR2TWCp77M) with populated places from [Natural Earth](https://www.naturalearthdata.com/downloads/110m-cultural-vectors/):

```
SELECT
    "name", 
    X(TRANSFORM("GEOMETRY", 4326)) as long,
    Y(TRANSFORM("GEOMETRY", 4326)) as lat
FROM "naturalearth_populated_places_3857"
```

It also has 4326 projection:
```

SELECT
    "name", 
    X("GEOMETRY") as long,
    Y("GEOMETRY") AS lat 
FROM "naturalearth_populated_places_4326"
```
