### ISSUE TITLE
Error loading Spatialite database

### ISSUE THREAD

**Issue by geraldo** [spaciandd/franchise#6]
Since the last commit https://github.com/geraldo/franchise-1/commit/2bca289d46d02fb1ab2de4f75778765b8c4fb8c1 the following error does show (index.js line 350) up when loading the [Spatialite database I'm regularly working with](https://cloud.servus.at/s/kfZ4fCHTdsR8SEZ) (note: you have to edit file size limit [here](https://github.com/spaciandd/franchise/blob/main/src/db/sqlite/index.js#L288) as the file is almost 30MB):

Firefox:
> TypeError: ast.statement[0].definition is undefined

Chrome:
> TypeError: Cannot read properties of undefined (reading 'filter')

I few lines before, this error does show up, but I'm not sure if it is related:

> InitSpatiaMetaData() error:"table spatial_ref_sys already exists"

**Comment by spaciandd** [comment]
Added try catch for **spatial_ref_sys** and also added check for **ast.statement[0].definition**, it was occuring because of virtual entities were present in db.

**Comment by geraldo** [comment]
Great, thanks! It does load now and I can run queries like that:
```
SELECT
    "name", 
    X(transform(geometry, 4326)) AS long,
    Y(transform(geometry, 4326)) AS lat
FROM "campogrande"
```
