### ISSUE TITLE
Doubt: Which tables should show up?

### ISSUE THREAD

**Issue by geraldo** [spaciandd/franchise#7]
For this [small test database](https://cloud.servus.at/s/F5o2MjR2TWCp77M) with populated places from [Natural Earth](https://www.naturalearthdata.com/downloads/110m-cultural-vectors/) 3 tables do show up:

![image](https://user-images.githubusercontent.com/336371/158971184-fc0c24ce-4666-47a2-a600-8e1b47ccfd23.png)

Geometry queries do work fine when running on tables _naturalearth_populated_places_4326_ and _naturalearth_populated_places_3857_, but not on table _ne_cities_.

So my question is: What is the table _ne_cities_ good for?

**Comment by spaciandd** [comment]
Result of following query will be list of tables, except the virtual tables,

`SELECT name, sql FROM sqlite_master where type = 'table' and tbl_name not like 'idx_%' and tbl_name not like 'rtree_%' and tbl_name not like 'gpkg_%' and tbl_name not in ('spatial_ref_sys', 'spatialite_history', 'sqlite_sequence', 'geometry_columns', 'spatial_ref_sys_aux', 'views_geometry_columns', 'virts_geometry_columns', 'geometry_columns_statistics', 'views_geometry_columns_statistics', 'virts_geometry_columns_statistics', 'geometry_columns_field_infos', 'views_geometry_columns_field_infos', 'virts_geometry_columns_field_infos', 'geometry_columns_time', 'geometry_columns_auth', 'views_geometry_columns_auth', 'virts_geometry_columns_auth', 'sql_statements_log', 'SpatialIndex', 'ElementaryGeometries');`

Now the result of above query, generates following result for [sample database](https://cloud.servus.at/s/F5o2MjR2TWCp77M), now as you can see 3 of them are virtual, so these will be excluded.

![Screenshot_1](https://user-images.githubusercontent.com/33995618/159137805-f79cc4bf-78d8-4bda-b555-434f386c88ba.png)
