### ISSUE TITLE
Error messages don't show up

### ISSUE THREAD

**Issue by geraldo** [spaciandd/franchise#8]
In the original version error messages do show up in the console and below the query and the Run Query icon goes back to the original state:

![image](https://user-images.githubusercontent.com/336371/159289422-23c2f47b-9060-4184-b585-4a80337ade18.png)

In our version error messages do show up in the console, but not under the query. Additionally the Run Query icon stays on state running forever.

**Comment by spaciandd** [comment]
Now it is showing up and working as expected.
